/**
 * Centralized Fallback & Mock Fixtures for Offline / Unwired API Endpoints.
 * Ensures the Next.js Admin Panel renders graceful fallback states when
 * backend endpoints are offline, unreachable, or in development.
 */

import type {
  AdminStats,
  AdminUserRow,
  AdminUserDetail,
  AdminRisk,
  AdminRiskAlerts,
  RiskExposureItem,
  ChallengePlan,
  ChallengeAccount,
  Trade,
  AdminKycRow,
  AdminPayoutRow,
  PaymentOrder,
  Banner,
  Coupon,
  AdminAffiliate,
  AnalyticsRevenue,
  AnalyticsGrowth,
  AnalyticsChallenges,
  Symbol,
  Competition,
  Ticket,
} from '@/types/api'

export const FALLBACK_ADMIN_STATS: AdminStats = {
  users: 1248,
  open_positions: 42,
  total_trades: 15420,
  total_pnl: 84250.5,
  active_challenges: 412,
  funded_accounts: 89,
  pending_payments: 5,
}

export const FALLBACK_ADMIN_USERS: AdminUserRow[] = [
  {
    user_id: 101,
    user_login: 'trader_pro',
    user_email: 'alex.trader@example.com',
    user_registered: '2026-01-15 10:30:00',
    balance: 105400.0,
    equity: 106250.5,
    margin_used: 1200.0,
    status: 'funded',
    account_id: 5001,
    active_challenges: 1,
    funded_challenges: 1,
  },
  {
    user_id: 102,
    user_login: 'fx_master',
    user_email: 'sarah.fx@example.com',
    user_registered: '2026-02-01 14:12:00',
    balance: 50000.0,
    equity: 51200.0,
    margin_used: 800.0,
    status: 'active',
    account_id: 5002,
    active_challenges: 1,
    funded_challenges: 0,
  },
  {
    user_id: 103,
    user_login: 'quant_dev',
    user_email: 'david.quant@example.com',
    user_registered: '2026-02-20 09:45:00',
    balance: 25000.0,
    equity: 23800.0,
    margin_used: 0.0,
    status: 'suspended',
    account_id: 5003,
    active_challenges: 0,
    funded_challenges: 0,
  },
]

export const FALLBACK_ADMIN_USER_DETAIL: AdminUserDetail = {
  user: {
    id: 101,
    username: 'trader_pro',
    email: 'alex.trader@example.com',
    display_name: 'Alex Trader',
    registered: '2026-01-15 10:30:00',
  },
  account: {
    status: 'active',
    balance: 105400.0,
    equity: 106250.5,
  },
  note: 'High volume trader, passed Phase 2 in 8 days.',
  challenges: [
    {
      id: 801,
      plan_id: 2,
      phase: 3,
      status: 'funded',
      starting_balance: 100000,
      current_balance: 105400,
      trading_days: 14,
      created_at: '2026-01-16 00:00:00',
      phase_started_at: '2026-02-01 00:00:00',
    },
  ],
  payments: [
    {
      id: 301,
      plan_id: 2,
      amount: '499.00',
      gateway: 'stripe',
      status: 'approved',
      created_at: '2026-01-15 10:35:00',
      reviewed_at: '2026-01-15 10:36:00',
    },
  ],
  payouts: [
    {
      id: 401,
      challenge_id: 801,
      amount_requested: '4320.00',
      trader_amount: '3456.00',
      status: 'paid',
      admin_note: 'Processed via USDT-TRC20',
      requested_at: '2026-02-10 12:00:00',
      reviewed_at: '2026-02-11 09:15:00',
    },
  ],
  kyc: {
    id: 901,
    status: 'approved',
    admin_note: 'Verified passport and utility bill',
    reviewed_at: '2026-01-16 11:00:00',
  },
  timeline: [
    { type: 'registered', label: 'User registered account', at: '2026-01-15 10:30:00' },
    { type: 'payment', label: 'Purchased 100K Evaluation Plan', at: '2026-01-15 10:35:00' },
    { type: 'kyc', label: 'KYC Verification Approved', at: '2026-01-16 11:00:00' },
    { type: 'passed', label: 'Passed Evaluation Phase 1', at: '2026-01-25 18:20:00' },
    { type: 'funded', label: 'Funded Account Granted', at: '2026-02-01 09:00:00' },
    { type: 'payout', label: 'Payout of $3,456.00 Completed', at: '2026-02-11 09:15:00' },
  ],
}

export const FALLBACK_ADMIN_RISK: AdminRisk = {
  funded_count: 89,
  funded_capital: 8900000,
  active_challenges: 412,
  pending_payout_value: 12500,
  pending_payout_count: 4,
  approved_payout_value: 145000,
  frozen_count: 2,
  banned_count: 1,
  near_breach: 6,
}

export const FALLBACK_RISK_ALERTS: AdminRiskAlerts = {
  hft_risks: [],
  gambling_risks: [],
  open_flags: 0,
}

export const FALLBACK_RISK_EXPOSURE: RiskExposureItem[] = [
  { symbol: 'EURUSD', cmd: 'buy', total_lots: 42.5, trade_count: 18 },
  { symbol: 'GBPUSD', cmd: 'sell', total_lots: 28.0, trade_count: 12 },
  { symbol: 'BTCUSD', cmd: 'buy', total_lots: 15.2, trade_count: 8 },
  { symbol: 'XAUUSD', cmd: 'sell', total_lots: 35.0, trade_count: 14 },
]

export const FALLBACK_CHALLENGE_PLANS: ChallengePlan[] = [
  {
    id: 1,
    name: 'Starter 10K',
    slug: 'starter-10k',
    account_size: 10000,
    price: 99,
    currency: 'USD',
    phases: 2,
    is_instant_funding: 0,
    drawdown_type: 'static',
    p1_profit_target: 8,
    p1_daily_dd: 5,
    p1_max_dd: 10,
    p1_min_days: 5,
    p1_max_days: 30,
    p2_profit_target: 5,
    p2_daily_dd: 5,
    p2_max_dd: 10,
    p2_min_days: 5,
    p2_max_days: 60,
    p3_profit_target: 0,
    p3_daily_dd: 0,
    p3_max_dd: 0,
    p3_min_days: 0,
    p3_max_days: 0,
    funded_profit_split: 80,
    funded_max_dd: 10,
    max_leverage: 100,
    max_lot_size: 10,
    news_trading: 1,
    weekend_holding: 1,
    consistency_rule: 0,
    consistency_pct: 0,
    ea_allowed: 1,
    hedging_allowed: 1,
    copy_trading_allowed: 0,
    stop_loss_required: 0,
    max_inactivity_days: 30,
    ip_matching_required: 1,
    martingale_allowed: 0,
    refundable_fee: 1,
    news_window_minutes: 2,
    evaluation_profit_share: 0,
    min_trade_seconds: 0,
    margin_call_level: 50,
    scaling_enabled: 1,
    scaling_growth_pct: 25,
    scaling_max_balance: 200000,
    scaling_interval_months: 3,
    scaling_required_profit_pct: 10,
    is_active: 1,
    sort_order: 1,
  },
  {
    id: 2,
    name: 'Pro 100K',
    slug: 'pro-100k',
    account_size: 100000,
    price: 499,
    currency: 'USD',
    phases: 2,
    is_instant_funding: 0,
    drawdown_type: 'static',
    p1_profit_target: 8,
    p1_daily_dd: 5,
    p1_max_dd: 10,
    p1_min_days: 5,
    p1_max_days: 30,
    p2_profit_target: 5,
    p2_daily_dd: 5,
    p2_max_dd: 10,
    p2_min_days: 5,
    p2_max_days: 60,
    p3_profit_target: 0,
    p3_daily_dd: 0,
    p3_max_dd: 0,
    p3_min_days: 0,
    p3_max_days: 0,
    funded_profit_split: 80,
    funded_max_dd: 10,
    max_leverage: 100,
    max_lot_size: 50,
    news_trading: 1,
    weekend_holding: 1,
    consistency_rule: 0,
    consistency_pct: 0,
    ea_allowed: 1,
    hedging_allowed: 1,
    copy_trading_allowed: 0,
    stop_loss_required: 0,
    max_inactivity_days: 30,
    ip_matching_required: 1,
    martingale_allowed: 0,
    refundable_fee: 1,
    news_window_minutes: 2,
    evaluation_profit_share: 0,
    min_trade_seconds: 0,
    margin_call_level: 50,
    scaling_enabled: 1,
    scaling_growth_pct: 25,
    scaling_max_balance: 1000000,
    scaling_interval_months: 3,
    scaling_required_profit_pct: 10,
    is_active: 1,
    sort_order: 2,
  },
]

export const FALLBACK_CHALLENGES: ChallengeAccount[] = [
  {
    id: 801,
    user_id: 101,
    plan_id: 2,
    fxsim_account_id: 5001,
    phase: 3,
    status: 'funded',
    starting_balance: 100000,
    current_balance: 105400,
    peak_balance: 107200,
    daily_start_balance: 104800,
    trading_days: 14,
    last_trade_date: '2026-02-12',
    breach_reason: null,
    breach_at: null,
    phase_started_at: '2026-02-01 00:00:00',
    phase_ends_at: null,
    passed_at: '2026-01-31 16:00:00',
    failed_at: null,
    funded_at: '2026-02-01 09:00:00',
    scaling_level: 0,
    last_scaled_at: null,
    created_at: '2026-01-16 00:00:00',
    plan_name: 'Pro 100K',
    account_size: 100000,
    funded_profit_split: 80,
  },
]

export const FALLBACK_TRADES: Trade[] = [
  {
    id: 9001,
    account_id: 5001,
    symbol: 'EURUSD',
    type: 'buy',
    lot_size: 2.5,
    open_price: 1.085,
    close_price: 1.089,
    pnl: 1000.0,
    swap: 0.0,
    commission: 15.0,
    sl: 1.081,
    tp: 1.092,
    opened_at: '2026-02-12 10:00:00',
    closed_at: '2026-02-12 14:30:00',
  },
]

export const FALLBACK_KYC_ROWS: AdminKycRow[] = [
  {
    id: 901,
    user_id: 101,
    username: 'trader_pro',
    email: 'alex.trader@example.com',
    name: 'Alex Trader',
    status: 'pending',
    admin_note: null,
    submitted_at: '2026-02-13 08:00:00',
    reviewed_at: null,
    docs: {
      id_doc: '/uploads/kyc/id_101.png',
      selfie: '/uploads/kyc/selfie_101.png',
      address_doc: '/uploads/kyc/proof_101.pdf',
    },
  },
]

export const FALLBACK_PAYOUT_ROWS: AdminPayoutRow[] = [
  {
    id: 401,
    challenge_id: 801,
    user_id: 101,
    username: 'trader_pro',
    email: 'alex.trader@example.com',
    name: 'Alex Trader',
    amount_requested: 4320.0,
    trader_amount: 3456.0,
    firm_amount: 864.0,
    profit_split_pct: 80,
    status: 'pending',
    payment_method: 'usdt_trc20',
    payment_address: 'T9x...K8pQ',
    tx_reference: null,
    proof_url: null,
    admin_note: null,
    requested_at: '2026-02-13 11:30:00',
    processed_at: null,
  },
]

export const FALLBACK_PAYMENTS: PaymentOrder[] = [
  {
    id: 301,
    user_id: 101,
    plan_id: 2,
    amount: '499.00',
    gateway: 'stripe',
    status: 'approved',
    proof_url: null,
    admin_note: 'Verified Stripe Checkout',
    created_at: '2026-01-15 10:35:00',
    reviewed_at: '2026-01-15 10:36:00',
  },
]

export const FALLBACK_BANNERS: Banner[] = [
  {
    id: 1,
    title: 'Spring Prop Sale',
    message: 'Get 20% off all 100K evaluation accounts with code SPRING20',
    placement: 'top',
    scope_type: 'global',
    scope_path: null,
    bg_color: '#0f172a',
    text_color: '#00FF66',
    cta_label: 'Claim Discount',
    cta_url: '/checkout?coupon=SPRING20',
    coupon_code: 'SPRING20',
    starts_at: '2026-02-01',
    ends_at: '2026-03-01',
    countdown_to: null,
    active: 1,
    priority: 10,
  },
]

export const FALLBACK_COUPONS: Coupon[] = [
  {
    id: 1,
    code: 'SPRING20',
    type: 'percent',
    value: 20,
    currency: 'USD',
    expires_at: '2026-03-01',
    usage_limit: 500,
    per_user_limit: 1,
    plan_ids: null,
    active: 1,
    used_count: 42,
  },
]

export const FALLBACK_AFFILIATES: AdminAffiliate[] = [
  {
    id: 1,
    user_id: 101,
    code: 'ALEX10',
    rate_percent: 15,
    status: 'active',
    user_login: 'trader_pro',
    user_email: 'alex.trader@example.com',
    display_name: 'Alex Trader',
    conversions: 12,
    total: 1450.0,
    paid: 950.0,
    unpaid: 500.0,
    referrals: 38,
  },
]

export const FALLBACK_ANALYTICS_REVENUE: AnalyticsRevenue = {
  monthly: [
    { month: '2025-11', count: 45, total: 18450 },
    { month: '2025-12', count: 62, total: 24800 },
    { month: '2026-01', count: 88, total: 36200 },
    { month: '2026-02', count: 104, total: 42100 },
  ],
  by_plan: [
    { plan_name: 'Starter 10K', sales: 120, revenue: 11880 },
    { plan_name: 'Pro 100K', sales: 180, revenue: 89820 },
  ],
  total: 121550,
}

export const FALLBACK_ANALYTICS_GROWTH: AnalyticsGrowth = {
  new_users: [
    { month: '2025-11', count: 120 },
    { month: '2025-12', count: 210 },
    { month: '2026-01', count: 350 },
    { month: '2026-02', count: 480 },
  ],
  new_challenges: [
    { month: '2025-11', count: 45 },
    { month: '2025-12', count: 62 },
    { month: '2026-01', count: 88 },
    { month: '2026-02', count: 104 },
  ],
  funded_monthly: [
    { month: '2025-11', count: 8 },
    { month: '2025-12', count: 14 },
    { month: '2026-01', count: 22 },
    { month: '2026-02', count: 31 },
  ],
  total_users: 1248,
  total_challenges: 412,
  total_funded: 89,
}

export const FALLBACK_ANALYTICS_CHALLENGES: AnalyticsChallenges = {
  status_counts: [
    { status: 'active', count: 210 },
    { status: 'passed', count: 65 },
    { status: 'failed', count: 120 },
    { status: 'funded', count: 89 },
  ],
  pass_rates: [
    {
      plan_name: 'Starter 10K',
      total: 120,
      passed: 24,
      failed: 76,
      avg_trading_days: 12,
      avg_pnl: 840,
    },
    {
      plan_name: 'Pro 100K',
      total: 180,
      passed: 41,
      failed: 94,
      avg_trading_days: 14,
      avg_pnl: 8200,
    },
  ],
  breach_reasons: [
    { breach_type: 'daily_drawdown', count: 85 },
    { breach_type: 'max_drawdown', count: 62 },
    { breach_type: 'inactivity', count: 18 },
  ],
  avg_days: [
    { phase: 1, avg_days: 9.4, count: 65 },
    { phase: 2, avg_days: 11.2, count: 45 },
  ],
}

export const FALLBACK_SYMBOLS: Symbol[] = [
  {
    id: 1,
    symbol: 'EURUSD',
    display_name: 'EUR / USD',
    type: 'forex',
    spread: 12,
    contract_size: 100000,
    min_lot: 0.01,
    max_lot: 50.0,
    digits: 5,
    swap_long: -3.2,
    swap_short: 1.1,
    is_active: 1,
    category: 'Majors',
  },
  {
    id: 2,
    symbol: 'GBPUSD',
    display_name: 'GBP / USD',
    type: 'forex',
    spread: 16,
    contract_size: 100000,
    min_lot: 0.01,
    max_lot: 50.0,
    digits: 5,
    swap_long: -4.5,
    swap_short: 1.8,
    is_active: 1,
    category: 'Majors',
  },
  {
    id: 3,
    symbol: 'BTCUSD',
    display_name: 'Bitcoin / USD',
    type: 'crypto',
    spread: 2500,
    contract_size: 1,
    min_lot: 0.01,
    max_lot: 10.0,
    digits: 2,
    swap_long: -15.0,
    swap_short: -15.0,
    is_active: 1,
    category: 'Crypto',
  },
]

export const FALLBACK_COMPETITIONS: Competition[] = [
  {
    id: 1,
    title: 'Summer Trading Championship 2026',
    name: 'Summer Trading Championship 2026',
    description: 'Compete against global traders for a $50,000 funded account purse!',
    start_date: '2026-06-01',
    end_date: '2026-06-30',
    prize_pool: '$50,000',
    starting_balance: 100000,
    initial_balance: 100000,
    max_participants: 2000,
    current_participants: 1420,
    entry_fee: 0,
    participants_count: 1420,
    status: 'upcoming',
  },
]

export const FALLBACK_TICKETS: Ticket[] = [
  {
    id: 101,
    ticket_number: 'TICK-101',
    trader_id: 101,
    user_id: 101,
    subject: 'Payout Request Verification Status',
    priority: 'medium',
    status: 'open',
    category: 'billing',
    created_at: '2026-02-13 09:00:00',
    updated_at: '2026-02-13 09:00:00',
    user_email: 'alex.trader@example.com',
    display_name: 'Alex Trader',
    latest_message: 'Hi, when will my USDT payout be processed?',
  },
]

export const FALLBACK_WHITELABEL: Record<string, string> = {
  brand_name: 'PropFirm FX',
  brand_tagline: 'Empowering Traders Worldwide',
  support_email: 'support@propfirmfx.com',
  primary_color: '#00FF66',
  secondary_color: '#0F172A',
  footer_text: '© 2026 PropFirm FX. All rights reserved.',
}

export const FALLBACK_AUDIT_LOG: unknown[] = [
  {
    id: 1,
    admin_id: 1,
    admin_name: 'System Admin',
    action: 'payout_approved',
    details: 'Approved payout #401 for Alex Trader ($3,456.00)',
    created_at: '2026-02-11 09:15:00',
  },
  {
    id: 2,
    admin_id: 1,
    admin_name: 'System Admin',
    action: 'kyc_approved',
    details: 'Approved KYC for Alex Trader',
    created_at: '2026-01-16 11:00:00',
  },
]
